### PR TITLE
:sparkles: 'kflex' brew formula

### LINKED ISSUE #271: feature: command is called 'kflex' but brew formula is called 'kubeflex' - pick one please
### Feature Description

I went to upgrade 'kflex'

brew upgrade kflex                                                                                               
Error: No available formula with the name "kflex". Did you mean flex or jflex?

I found out I needed to upgrade 'kubeflex'

but the command for kubeflex is 'kflex'

### Proposed Solution

it would be good to name the formula the same as the command or vice-a-versa so there is less confusion.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by algoritmoalex**
## Summary
With these changes:
- our users can use `kubeflex` and/or `kflex` formulas
- kubestellar documentation changes are minimal
- a date can be set for a planned shutdown of the `kubeflex` formula if needed

```sh
brew install kflex
# shows one can install kubeflex with kflex alias
```

image

```sh
brew upgrade kflex
# shows one can upgrade kubeflex with kflex alias
```

image

### Special consideration
Both `kubeflex.rb` and `kflex.rb` brew formulas must be maintained.

## Related issue(s)

Fixes #271

### CODE REVIEW

**Review by pdettori — COMMENTED** [review]
@algoritmoalex thank you for submitting this PR. Please note that the kflex.rb file should not be edited directly as it is managed by go releaser, and it is automatically created for each new release. See https://github.com/kubestellar/kubeflex/blob/ee326624021341a3d9053759cf39aef2ef99e6f9/.goreleaser.yaml#L58-L68 for the relevant goreleaser code. You can find all the Go releaser brew options here: https://goreleaser.com/customization/homebrew/

**Comment by algoritmoalex** [comment]
@pdettori thanks for the clarification. I will review the Go Releaser options and edit over the next few days. For now I have converted the PR to a draft. Please let me know if it is better to close this PR and open a new one instead.

**Comment by pdettori** [comment]
> @pdettori thanks for the clarification. I will review the Go Releaser options and edit over the next few days. For now I have converted the PR to a draft. Please let me know if it is better to close this PR and open a new one instead.

Thank you @algoritmoalex, both approaches work for me, you may pick the one that works best for you, Thanks!

**Comment by pdettori** [comment]
closing as it needs to be re-created with a different approach as outlined on last comment

**Pull request closed without merging**
