### PR TITLE
✨ Separate CRDs

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Updated the `Makefile` and kustomizer to separate the CRDs of the helm from the `operator.yaml`

CRDs installed by an helm chart should be included in the special chart/crds/ folder to make sure that Helm installs them first, before acting on the rest of the chart.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@francostellari Can you please add couple of lines to the description about the reason to do this ?

**Comment by francostellari** [comment]
> @francostellari Can you please add couple of lines to the description about the reason to do this ?

@ezrasilvera I have updated the comment as you requested:

CRDs installed by an helm chart should be included in the special chart/crds/ folder to make sure that Helm installs them first, before acting on the rest of the chart.

**Review by pdettori — APPROVED** [review]
/lgtm

**Comment by francostellari** [comment]
@pdettori please note that @MikeSpreitzer requested a different approach used for the status-addon: https://github.com/kubestellar/ocm-status-addon/pull/47/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
Let me know if you want me to match it here

**Comment by pdettori** [comment]
> @pdettori please note that @MikeSpreitzer requested a different approach used for the status-addon: 

@francostellari is the difference about the use of yq ? I am fine both ways, so let's leave this as it is.

**Comment by francostellari** [comment]
@pdettori ok

**Pull request merged**
