### PR TITLE
✨ add conditions in status

### PR DESCRIPTION
**Pull request by pdettori**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by waltforme** [comment]
Quick question: is `api/v1alph1/conditions.go` written by some code-gen or created by hand?

**Comment by pdettori** [comment]
It’s written by hand. Not sure there are generators to produce conditions. Some frameworks like Crossplane provide conditions when extending their API.

**Comment by waltforme** [comment]
I see. Thanks for letting me know these!

**Comment by pdettori** [comment]
You are welcome @waltforme

**Pull request merged**
